### ISSUE TITLE
add "run tests" info to docs, run `pytest` tests in gh action

### ISSUE THREAD

**Issue by mnyrop** [nyudlts/ultraviolet#85]
- [x] add "run tests" info to docs @ekate 
- [x] run `pytest` tests in gh action @mnyrop 

(should happen after #84 is merged since it scaffolds the "run tests" page)

**Comment by ekate** [comment]
@mnyrop I just added some "draft" of a "draft" [here](https://github.com/nyudlts/ultraviolet/blob/docs/testing/docs/deployment/index.md) . I will modify it but just want to know if it is enough information for you or you need more ?

**Comment by Sinclert** [comment]
Something to consider for the completion of this issue:

Turns out the several services (_Redis_, _ElasticSearch_, _PostgreSQL_...) in which Invenio instances depend, **would need to be running** for the tests to successfully run (at least those regarding UI stuff). We could take a look at how HEPData (another Invenio-based project) does this on its [GitHub Action testing workflow](https://github.com/HEPData/hepdata/blob/master/.github/workflows/ci.yml#):

https://github.com/HEPData/hepdata/blob/90b11bb6186d3860aeb660d269c5e9f4fe0c5215/.github/workflows/ci.yml#L48-L78
